title: Adv. Prog. (Modern C++)
description: Modern C++ for Advanced Programming Course, FUM, CS Dept.
theme: just-the-docs

url: https://fum-cs.github.io/modern-cpp

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/fum-cs-blue.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/logo-small.ico"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
